name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Lint (ruff)
        run: ruff check .
      - name: Type check (mypy)
        run: mypy .
      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings --cov=options_engine
      - name: Build wheel and sdist
        run: python -m build
      - name: Build docker image
        run: docker build . -f docker/Dockerfile
