name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install .[dev]
      - name: Static analysis (Bandit)
        run: bandit -r src -ll
      - name: SAST (Semgrep)
        run: semgrep --config .semgrep.yaml --error
      - name: Lint (ruff)
        run: ruff check .
      - name: Type check (mypy)
        run: mypy .
      - name: Dependency audit (pip-audit)
        run: pip-audit --strict
      - name: Generate SBOM (CycloneDX)
        run: cyclonedx-bom -o sbom.json -F json
      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings --cov=options_engine
      - name: Build wheel and sdist
        run: python -m build
      - name: Build docker image
        run: docker build . -f docker/Dockerfile -t options-pricing-engine:ci
      - name: Container scan (Trivy)
        run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:0.49.1 image --exit-code 1 --ignore-unfixed options-pricing-engine:ci
      - name: Container scan (Grype)
        run: docker run --rm -v /var/run/docker.sock:/var/run/docker.sock anchore/grype:0.72.0 options-pricing-engine:ci --fail-on high
